// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Bilog.Data.Models
{
    public partial class Comment
    {
        public Comment()
        {
            InverseParentComment = new HashSet<Comment>();
        }

        [Key]
        public int CommentId { get; set; }
        public int BlogId { get; set; }
        public int? ParentCommentId { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public string CommentUserId { get; set; }
        public string Content { get; set; }
        public DateTime CommentCreated { get; set; }
        public DateTime? CommentUpdated { get; set; }
        public string CommentIpaddress { get; set; }

        public virtual Blogs Blog { get; set; }
        public virtual Comment ParentComment { get; set; }
        public virtual ICollection<Comment> InverseParentComment { get; set; }
    }
}